# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: arm
      goarm: 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-{{.Commit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"
brews:
  -
    name: terraform-provider-kafka
    github:
      owner: packetloop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/packetloop/terraform-provider-kafka"
    url_template: "https://github.com/packetloop/terraform-provider-kafka/releases/v{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    commit_author:
      name: Arbor Networks
      email: mayhem@arbor.net
    caveats: "How to use this binary"
    description: "Terraform provider for Kafka"
    skip_upload: true
    dependencies:
      - git
      - zsh
    conflicts:
      - svn
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
    test: |
      system "#{bin}/program --version"
    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "program"
  